/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gmc.learning.kafka.avro.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TestTemplate extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8037701864368342438L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TestTemplate\",\"namespace\":\"gmc.learning.kafka.avro.schema\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"doc\":\"Id of the filed\"},{\"name\":\"message\",\"type\":\"string\",\"doc\":\"message\"}],\"version\":\"1\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TestTemplate> ENCODER =
      new BinaryMessageEncoder<TestTemplate>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TestTemplate> DECODER =
      new BinaryMessageDecoder<TestTemplate>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TestTemplate> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TestTemplate> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TestTemplate>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TestTemplate to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TestTemplate from a ByteBuffer. */
  public static TestTemplate fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Id of the filed */
  @Deprecated public java.lang.CharSequence id;
  /** message */
  @Deprecated public java.lang.CharSequence message;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TestTemplate() {}

  /**
   * All-args constructor.
   * @param id Id of the filed
   * @param message message
   */
  public TestTemplate(java.lang.CharSequence id, java.lang.CharSequence message) {
    this.id = id;
    this.message = message;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return message;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: message = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return Id of the filed
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * Id of the filed
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return message
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }

  /**
   * Sets the value of the 'message' field.
   * message
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Creates a new TestTemplate RecordBuilder.
   * @return A new TestTemplate RecordBuilder
   */
  public static gmc.learning.kafka.avro.schema.TestTemplate.Builder newBuilder() {
    return new gmc.learning.kafka.avro.schema.TestTemplate.Builder();
  }

  /**
   * Creates a new TestTemplate RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TestTemplate RecordBuilder
   */
  public static gmc.learning.kafka.avro.schema.TestTemplate.Builder newBuilder(gmc.learning.kafka.avro.schema.TestTemplate.Builder other) {
    return new gmc.learning.kafka.avro.schema.TestTemplate.Builder(other);
  }

  /**
   * Creates a new TestTemplate RecordBuilder by copying an existing TestTemplate instance.
   * @param other The existing instance to copy.
   * @return A new TestTemplate RecordBuilder
   */
  public static gmc.learning.kafka.avro.schema.TestTemplate.Builder newBuilder(gmc.learning.kafka.avro.schema.TestTemplate other) {
    return new gmc.learning.kafka.avro.schema.TestTemplate.Builder(other);
  }

  /**
   * RecordBuilder for TestTemplate instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TestTemplate>
    implements org.apache.avro.data.RecordBuilder<TestTemplate> {

    /** Id of the filed */
    private java.lang.CharSequence id;
    /** message */
    private java.lang.CharSequence message;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(gmc.learning.kafka.avro.schema.TestTemplate.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.message)) {
        this.message = data().deepCopy(fields()[1].schema(), other.message);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TestTemplate instance
     * @param other The existing instance to copy.
     */
    private Builder(gmc.learning.kafka.avro.schema.TestTemplate other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.message)) {
        this.message = data().deepCopy(fields()[1].schema(), other.message);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * Id of the filed
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * Id of the filed
      * @param value The value of 'id'.
      * @return This builder.
      */
    public gmc.learning.kafka.avro.schema.TestTemplate.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * Id of the filed
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * Id of the filed
      * @return This builder.
      */
    public gmc.learning.kafka.avro.schema.TestTemplate.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * message
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }

    /**
      * Sets the value of the 'message' field.
      * message
      * @param value The value of 'message'.
      * @return This builder.
      */
    public gmc.learning.kafka.avro.schema.TestTemplate.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.message = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * message
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'message' field.
      * message
      * @return This builder.
      */
    public gmc.learning.kafka.avro.schema.TestTemplate.Builder clearMessage() {
      message = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TestTemplate build() {
      try {
        TestTemplate record = new TestTemplate();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.message = fieldSetFlags()[1] ? this.message : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TestTemplate>
    WRITER$ = (org.apache.avro.io.DatumWriter<TestTemplate>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TestTemplate>
    READER$ = (org.apache.avro.io.DatumReader<TestTemplate>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
